### ISSUE TITLE
Commented build commands

### ISSUE THREAD

**Issue by ipa-rmb** [ipa320/cob_object_perception#43]
cob_surface_classification is still a problem - thus commented out - due to (yet) unresolvable dependencies to cob_3d_XXX packages...I suggest to merge this PR and resolve that in a new PR!

same holds true for cob_read_text_data and cob_tesseract_data

**Comment by fmessmer** [comment]
Although `cob_3d_mapping_msgs` has been moved into `cob_perception_common` in 
https://github.com/ipa320/cob_perception_common/pull/60 and https://github.com/ipa320/cob_environment_perception/pull/35, it does not allow to comment back in the code as there are still dependencies to e.g. `cob_3d_mapping_common`

**Comment by ipa-rmb** [comment]
Problems solved by #48 .
