### ISSUE TITLE
Build issues in Groovy - PR2

### ISSUE THREAD

**Issue by Telpr2** [ipa320/cob_object_perception#44]
Hi  we are working on PR2 with groovy distribution. Have to read text using Kinect. We couldnt find literate_pr2 stack to download. Then figured out cob_read_text can help us in accomplishing the same. Have downloaded cob_object_perception for groovy_dev. But we are getting multiple build errors mainly in Leptonica, Tesseract and Libzxing. The link "https://code.ros.org/svn/release/download/thirdparty/" is not active now. How to rectify it? should we change the version of Leptonica andTesseract? Can you please help us. New to ROS. Can you please provide us with the stack and instructions so that we can be successful in making PR2 read text using kinect. Thanks in advance. Awaiting your response at the earliest.

**Comment by ipa-rmb** [comment]
Alright folks, you are right, our old file repository is not online anymore. We do not support groovy anymore, however, it seems like you can fix your problem simply by changing the download links for the library archives into:
https://github.com/ipa320/thirdparty/raw/master/leptonica-$(TARBALL_VERSION).tar.gz
https://github.com/ipa320/thirdparty/raw/master/tesseract-ocr-rev$(TARBALL_REVISION).tar.gz
https://github.com/ipa320/thirdparty/raw/master/zxing-2.1.tar.gz

Please see the indigo_dev version of
https://github.com/ipa-rmb/cob_extern
https://github.com/ipa-rmb/cob_object_perception
for further details.

Best regards,
Richard

**Comment by Telpr2** [comment]
Thanks a lot for the download links .Can you please let us know the steps to be followed in detail if we need to read text from camera/kinect . As there are no detailed description or readme available. Also If you have access to literate_pr2 stack can you please provide us with that.  Thanks in advance.

**Comment by ipa-rmb** [comment]
We unfortunately do not have access to the literate_pr2 stack, maybe you can ask the developer of this software. I assume, our software is currently configured for database testing. I might have time next week to look into the question how to select camera-based reading. Anyways, this software is in a very experimental state and far from being ready for end-user use. That's why there is no readme or any other instructions.

**Comment by mgruhler** [comment]
As the installation issue seems to be fixed, I'll close this PR. Feel free to reopen, if there are still problems.
