### ISSUE TITLE
migrate to kinetic

### ISSUE THREAD

**Issue by fmessmer** [ipa320/cob_object_perception#47]
in #46 Travis CI tests showed that this branch needs to properly be migrated to kinetic/xenial on a new `kinetic_dev` branch

**Comment by fmessmer** [comment]
from #54 
 - fix https://travis-ci.org/ipa320/cob_object_perception/jobs/259286246#L2140
 - also use proper Eigen migration (`cmake_module` is deprecated) https://travis-ci.org/ipa320/cob_object_perception/jobs/259286246#L2124

**Comment by ipa-rmb** [comment]
done with #55
