### ISSUE TITLE
Missing run_detect

### ISSUE THREAD

**Issue by Panos68** [ipa320/cob_object_perception#49]
Hello,
I am trying to use the package but i get an error that it misses something. It says that can't locate node **run_detect** in package cob_read_text

**Comment by ipa-rmb** [comment]
I have updated my branch: https://github.com/ipa-rmb/cob_object_perception.git . Please update your code from there. To avoid downloading further dependencies, you may put a CATKIN_IGNORE file into the following packages: cob_surface_classification, cob_texture_categorization. The names of the built executables were indeed wrong. It is all corrected now. You may start a kinect (or any other camera) and then start the program with roslaunch cob_read_text read_text_from_camera.launch (maybe adapt the camera topic name in the launch file first). This worked for me. However, Tesseract OCR appeared to be very slow in the current version, I do not know yet how to speed this up. Furthermore, this code is work in progress and that is the reason why there is no documentation. You may use it but we do not intend it to be used by external people yet.

**Comment by Panos68** [comment]
Hello again and thank you for your reply. For the speed i need to check how slow is because actually its the only package that serves my scope so even if its slow it might be useful.

I am new in Ros but i manage to work the camera with other packages so i know its working properly. I catkin_make --only--packages--with--dependencies all the files and then i run the command about the camera.launch and i got the following error. 

Correlation:/home/panos/catkin_ws/src/cob_perception_data-indigo_dev/cob_read_text_data/fonts/new_correlation.txt
cob_read_text: /home/panos/catkin_ws/src/cob_object_perception-indigo_dev/cob_read_text/common/src/text_detect.cpp:122: void DetectText::readLetterCorrelation(const char*): Assertion `fin >> number' failed.
[cob_read_text-2] process has died [pid 30418, exit code -6, cmd /home/panos/catkin_ws/devel/lib/cob_read_text/cob_read_text /home/panos/catkin_ws/src/cob_perception_data-indigo_dev/cob_read_text_data/fonts/new_correlation.txt /home/panos/catkin_ws/src/cob_perception_data-indigo_dev/cob_read_text_data/dictionary/full-dictionary_eng text_detect:=/read_text/text_detect image_color:=/camera/rgb/image_raw __name:=cob_read_text __log:=/home/panos/.ros/log/9123a7fe-3d47-11e7-9291-848f69c69340/cob_read_text-2.log].
log file: /home/panos/.ros/log/9123a7fe-3d47-11e7-9291-848f69c69340/cob_read_text-2*.log

**Comment by ipa-rmb** [comment]
Did you clone the repository https://github.com/ipa-rmb/cob_perception_data.git ? If this data repository is not on your disk, it won't work.

**Comment by Panos68** [comment]
Yes they are both in the same folder

**Comment by ipa-rmb** [comment]
Is your folder really called cob_perception_data-indigo_dev? Please check whether the path to the file (Correlation:/home/panos/catkin_ws/src/cob_perception_data-indigo_dev/cob_read_text_data/fonts/new_correlation.txt) really fits the situation on your disk. If yes, you may check and debug the referenced function where the error occurs since I could not repeat that error on a completely fresh installation on a different PC. Maybe you remove the assert from line 122: assert(fin >> number); . And then add a display output for the read number, e.g. std::cout << number << "\t"; in order to see whether the numbers are read properly from that file.

However, as said, this package is work in progress which we unfortunately cannot give much support for at the moment.

**Comment by Panos68** [comment]
For the correlation the file wasnt new_correlation but correlation so i renamed it. Moreover by removing the assert from line 122 the package worked. The problem is it gets many times a loop of invalid characters and stucks. But ok because its a work in progress i close the issue and thank you for the help
