### ISSUE TITLE
cob_fiducials sometimes crashes

### ISSUE THREAD

**Issue by ipa-rmb-pz** [ipa320/cob_object_perception#57]
[ INFO] [1509970032.546681698]: [fiducials] color image callback
OpenCV Error: Assertion failed (blockSize % 2 == 1 && blockSize > 1) in adaptiveThreshold, file /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/thresh.cpp, line 797
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/thresh.cpp:797: error: (-215) blockSize % 2 == 1 && blockSize > 1 in function adaptiveThreshold

[fiducials/fiducials-1] process has died [pid 27941, exit code -6, cmd /u/order-picking/git/care-o-bot/devel/lib/cob_fiducials/fiducials image_color:=/camera/color_image camera_info:=/camera/depth_registered/camera_info detect_fiducials:=/fiducials/detect_fiducials fiducial_markers:=/fiducials/fiducial_markers image:=/fiducials/image get_fiducials:=/fiducials/get_fiducials __name:=fiducials __log:=/u/order-picking/.ros/log/9c83b86c-c2dc-11e7-9701-00c08800b220/fiducials-fiducials-1.log].
log file: /u/order-picking/.ros/log/9c83b86c-c2dc-11e7-9701-00c08800b220/fiducials-fiducials-1*.log
all processes on machine have died, roslaunch will exit

**Comment by ipa-rmb** [comment]
Was not observed again, maybe fixed by the latest bugfixes.
